### PR TITLE
Thanks for the challenge :)

### PR DESCRIPTION
**Pull request by alexpeak**
Note that I was getting some false failures from doctest due to the spacing around the markdown code-blocks, I fixed this in the first commit.

### CODE REVIEW

**Comment by mshang** [comment]
Yikes, sorry about the spacing. Nicely done on the solution! You're the second person to submit a solution.

**Comment by mshang** [comment]
💯

**Comment by alexpeak** [comment]
That other guy was really on the ball, I can't read HN that fast :)

**Comment by pepsiman** [comment]
I saw it on Facebook :)

**Pull request closed without merging**
