### PR TITLE
Implement ElevatorLogic

### PR DESCRIPTION
**Pull request by pepsiman**

### CODE REVIEW

**Comment by mshang** [comment]
It doesn't seem to pass the doctests. Have you run this?

```
python -m doctest README.md
```

**Comment by pepsiman** [comment]
```
1 items passed all tests:
 212 tests in README.md
212 tests in 1 items.
212 passed and 0 failed.
Test passed.
```

**Comment by pepsiman** [comment]
```
$ python --version
Python 2.7.6
```

**Comment by mshang** [comment]
Yup, I was testing the wrong branch.
First solution! Congrats and thanks for tackling this.
Send me an email and I'll send you an Amazon gift card as a small reward. My email is in my profile.

**Comment by pablodenadai** [comment]
Nice one! :tada:

**Pull request closed without merging**
